#pragma once

#include "util/Joaat.hpp"

#include <string>
#include <vector>


namespace YimMenu::Rewards
{
	struct RewardInfo
	{
		joaat_t model_hash;
		joaat_t reward_hash;
		std::string description;
	};
	inline const RewardInfo GoldRewards[]{{"mp001_s_mp_boxsm01x"_J, "mp001_s_mp_boxsm01x"_J, "Reward Box"}};

	inline const RewardInfo Heirlooms[]{{"MP005_S_HL_BR_BOARBRISTLE"_J, "PROVISION_HRLM_BRUSH_BOAR"_J, "Boar Bristle Brush"}, {"MP005_S_HL_BR_EBNY"_J, "PROVISION_HRLM_BRUSH_EBONY"_J, "Ebony Hairbrush"}, {"MP005_S_HL_BR_GOAT"_J, "PROVISION_HRLM_BRUSH_GOATHAIR"_J, "Goat Hair Brush"}, {"MP005_S_HL_BR_HORSE"_J, "PROVISION_HRLM_BRUSH_HORSEHAIR"_J, "Horse Hair Brush"}, {"MP005_S_HL_BR_NG_RSEWD"_J, "PROVISION_HRLM_BRUSH_ROSEWOOD_NG"_J, "New Guinea Rosewood Brush"}, {"MP005_S_HL_BR_RSEWD"_J, "PROVISION_HRLM_BRUSH_ROSEWOOD"_J, "Rosewood Brush"}, {"MP005_S_HL_CMB_BOXWOOD"_J, "PROVISION_HRLM_COMB_BOXWOOD"_J, "Boxwood Comb"}, {"MP005_S_HL_CMB_CHRYWD"_J, "PROVISION_HRLM_COMB_CHERRYWOOD"_J, "Cherrywood Comb"}, {"MP005_S_HL_CMB_IVRY"_J, "PROVISION_HRLM_COMB_IVORY"_J, "Ivory Comb"}, {"MP005_S_HL_CMB_TORTSHELL"_J, "PROVISION_HRLM_COMB_TORTOISESHELL"_J, "Tortoiseshell Comb"}, {"MP005_S_HL_HP_CRVDWD"_J, "PROVISION_HRLM_HAIRPIN_WOODEN"_J, "Carved Wood Hairpin"}, {"MP005_S_HL_HP_EBNY"_J, "PROVISION_HRLM_HAIRPIN_EBONY"_J, "Ebony Hairpin"}, {"MP005_S_HL_HP_IVRY"_J, "PROVISION_HRLM_HAIRPIN_IVORY"_J, "Ivory Hairpin"}, {"MP005_S_HL_HP_JDE"_J, "PROVISION_HRLM_HAIRPIN_JADE"_J, "Jade Hairpin"}, {"MP005_S_HL_HP_MTL"_J, "PROVISION_HRLM_HAIRPIN_METAL"_J, "Metal Hairpin"}};

	inline const RewardInfo Coins[]{{"MP005_S_CN_1700_NYT"_J, "PROVISION_COIN_1700_NY_TKN"_J, "1700 New Yorke Token"}, {"MP005_S_CN_1787_1C_APT"_J, "PROVISION_COIN_1787_CENT_TKN"_J, "1787 One Cent Token"}, {"MP005_S_CN_1789_PCTM"_J, "PROVISION_COIN_1789_PNY"_J, "1789 Penny"}, {"MP005_S_CN_1792_1866_5CNICK"_J, "PROVISION_COIN_1792_NICKEL"_J, "1792 Nickel"}, {"MP005_S_CN_1792_1870_QPD"_J, "PROVISION_COIN_1792_QTR"_J, "1792 Quarter"}, {"MP005_S_CN_1792_QLP"_J, "PROVISION_COIN_1792_LIB_QTR"_J, "1792 Liberty Quarter"}, {"MP005_S_CN_1794_1795_SD_FH"_J, "PROVISION_COIN_1794_SLV_DLR"_J, "1794 Silver Dollar"}, {"MP005_S_CN_1795_1797_5D_SHETR"_J, "PROVISION_COIN_1795_HLF_EAG"_J, "1795 Half Eagle"}, {"MP005_S_CN_1796_HALFPEN_CTN"_J, "PROVISION_COIN_1796_HLF_PNY"_J, "1796 Halfpenny"}, {"MP005_S_CN_1797_1804_10D_LC"_J, "PROVISION_COIN_1797_GLD_EAG"_J, "1797 Gold Eagle"}, {"MP005_S_CN_1798_1804_SD_DB"_J, "PROVISION_COIN_1798_SLV_DLR"_J, "1798 Draped Bust Silver Dollar"}, {"MP005_S_CN_1800_1805_S5C_DBHD"_J, "PROVISION_COIN_1800_HLF_DIME"_J, "1800 Half Dime"}, {"MP005_S_CN_1800_1888_5D_CB"_J, "PROVISION_COIN_1800_FIVE_DLR"_J, "1800 Five Dollar Bechtler"}, {"MP005_S_CN_1800_1899_25C_SG"_J, "PROVISION_COIN_1800_GLD_QTR"_J, "1800 Gold Quarter"}, {"MP005_S_CN_1800_1899_GD_LO"_J, "PROVISION_COIN_1800_GLD_DLR"_J, "1800 Gold Dollar"}};

	inline const RewardInfo AlcBottles[]{{"MP005_S_AWB_C"_J, "CONSUMABLE_COGNAC"_J, "Cognac"}, {"MP005_S_AWB_CB"_J, "CONSUMABLE_CYPRUS_BRANDY"_J, "Absinthe"}, {"MP005_S_AWB_CR"_J, "CONSUMABLE_CARIB_RUM"_J, "Carribean Rum"}, {"MP005_S_AWB_IW"_J, "CONSUMABLE_IRISH_WHISKEY"_J, "Irish Whisky"}, {"MP005_S_AWB_LDG"_J, "CONSUMABLE_LONDRY_GIN"_J, "London Dry Gin"}, {"MP005_S_AWB_OTG"_J, "CONSUMABLE_OLDTOM_GIN"_J, "Old Tom Gin"}, {"MP005_S_AWB_PG"_J, "CONSUMABLE_PLYMOUTH_GIN"_J, "Gran Corazon Madeira"}, {"MP005_S_AWB_SW"_J, "CONSUMABLE_SCOTCH_WHISKEY"_J, "Scotch Whisky"}, {"MP005_S_AWB_TW"_J, "CONSUMABLE_TENN_WHISKEY"_J, "Tennessee Whiskey"}};

	inline const RewardInfo Arrowheads[]{{"MP005_MP_AWHD_AGATE"_J, "PROVISION_ARROWHEAD_AGATE"_J, "Agate Arrowhead"}, {"MP005_MP_AWHD_BONE"_J, "PROVISION_ARROWHEAD_BONE"_J, "Bone Arrowhead"}, {"MP005_MP_AWHD_CHIPPED"_J, "PROVISION_ARROWHEAD_CHIPPED"_J, "Chipped Arrowhead"}, {"MP005_MP_AWHD_CRUDE"_J, "PROVISION_ARROWHEAD_CRUDE"_J, "Crude Arrowhead"}, {"MP005_MP_AWHD_FELDSPAR"_J, "PROVISION_ARROWHEAD_FELDSPAR"_J, "Feldspar Arrowhead"}, {"MP005_MP_AWHD_GRANITE"_J, "PROVISION_ARROWHEAD_FLINT"_J, "Granite Arrowhead"}, {"MP005_MP_AWHD_OBSIDIAN"_J, "PROVISION_ARROWHEAD_OBSIDIAN"_J, "Obsidian Arrowhead"}, {"MP005_MP_AWHD_QUARTZ"_J, "PROVISION_ARROWHEAD_QUARTZ"_J, "Quartz Arrowhead"}, {"MP005_MP_AWHD_RAW"_J, "PROVISION_ARROWHEAD_RAW"_J, "Raw Arrowhead"}, {"MP005_MP_AWHD_ROUGH"_J, "PROVISION_ARROWHEAD_ROUGH"_J, "Rough Arrowhead"}, {"MP005_MP_AWHD_SLATE"_J, "PROVISION_ARROWHEAD_SLATE"_J, "Slate Arrowhead"}, {"MP005_MP_AWHD_SPLNTR"_J, "PROVISION_ARROWHEAD_SPLINTERED"_J, "Splinter Arrowhead"}};

	inline const RewardInfo Bracelets[]{{"MP005_S_BRCLT_DMD_GLD"_J, "PROVISION_JEWELRY_DMND_BNGLE_BRACELET"_J, "Abello Ruby Bangle Bracelet"}, {"MP005_S_BRCLT_EDW_PRL"_J, "PROVISION_JEWELRY_PEARL_BRACELET"_J, "Durant Pearl Bracelet"}, {"MP005_S_BRCLT_GLD"_J, "PROVISION_JEWELRY_CARVED_BRACELET"_J, "Elliston Carved Bracelet"}, {"MP005_S_BRCLT_GLD_BNGL"_J, "PROVISION_JEWELRY_GLD_BNGLE_BRACELET"_J, "Ojeda Rose Gold Bracelet"}, {"MP005_S_BRCLT_SAP"_J, "PROVISION_JEWELRY_SPHR_BRACELET"_J, "Greco Sapphire Bracelet"}, {"MP005_S_BRCLT_SAP_BNGL"_J, "PROVISION_JEWELRY_SPHR_BNGLE_BRACELET"_J, "Helena Sapphire Bracelet"}, {"MP005_S_BRCLT_SLV"_J, "PROVISION_JEWELRY_TURQUOISE_BRACELET"_J, "Infanta Turquoise Bracelet"}, {"MP005_S_BRCLT_SLV_BNGL"_J, "PROVISION_JEWELRY_GRNET_BRACELET"_J, "Hajnal Garnet Bangle Bracelet"}};

	inline const RewardInfo Earrings[]{{"MP005_S_ERRNG_CIT_DROP"_J, "PROVISION_JEWELRY_DROP_EARRING"_J, "Ursula Citrine Earrings"}, {"MP005_S_ERRNG_CRL_DNGL"_J, "PROVISION_JEWELRY_CORAL_DNGL_EARRING"_J, "Emmeline Coral Earrings"}, {"MP005_S_ERRNG_ELK_THT"_J, "PROVISION_JEWELRY_ELK_TOOTH_EARRING"_J, "Sterling Tooth Earrings"}, {"MP005_S_ERRNG_EMR"_J, "PROVISION_JEWELRY_EMERALD_EARRING"_J, "Dutchess Emerald Earrings"}, {"MP005_S_ERRNG_FLRL_DMD"_J, "PROVISION_JEWELRY_WHT_DMND_EARRING"_J, "Orchidee Diamond Earrings"}, {"MP005_S_ERRNG_GLD_PRL"_J, "PROVISION_JEWELRY_PEARL_EARRING"_J, "Josephine Pearl Earrings"}, {"MP005_S_ERRNG_GLD_RDY_DNGL"_J, "PROVISION_JEWELRY_RUDY_DNGL_EARRING"_J, "Beauchene Ruby Earrings"}, {"MP005_S_ERRNG_GRN_SLV"_J, "PROVISION_JEWELRY_GRNET_POST_EARRING"_J, "Harford Garnet Earrings"}, {"MP005_S_ERRNG_OLD_MINE"_J, "PROVISION_JEWELRY_DMND_PENDT_EARRING"_J, "Endicott Diamond Earrings"}, {"MP005_S_ERRNG_QNS_DMD"_J, "PROVISION_JEWELRY_QN_DMND_EARRING"_J, "Royal Victoria Diamond Earrings"}, {"MP005_S_ERRNG_TRQ_STUD"_J, "PROVISION_JEWELRY_TURQ_STUD_EARRING"_J, "Calumet Turquoise Earrings"}};

	inline const RewardInfo Necklaces[]{{"MP005_S_NKLC_BLK_PRL"_J, "PROVISION_JEWELRY_BLCK_PEARL_NECKLACE"_J, "Tuamotu Pearl Necklace"}, {"MP005_S_NKLC_GLD_AME"_J, "PROVISION_JEWELRY_AMETHYST_NECKLACE"_J, "Braxton Amethyst Necklace"}, {"MP005_S_NKLC_GLD_CROSS"_J, "PROVISION_JEWELRY_GLD_CROSS_NECKLACE"_J, "Ainsworth Cross Necklace"}, {"MP005_S_NKLC_GLD_LAV"_J, "PROVISION_JEWELRY_GLD_PENDT_NECKLACE"_J, "Gosselin White Gold Necklace"}, {"MP005_S_NKLC_MTHR_PRL"_J, "PROVISION_JEWELRY_MTHR_PEARL_NECKLACE"_J, "Pelle Pearl Necklace"}, {"MP005_S_NKLC_ORI_PRL"_J, "PROVISION_JEWELRY_GLD_PEARL_NECKLACE"_J, "Rou Pearl Necklace"}, {"MP005_S_NKLC_PLT_TPZ"_J, "PROVISION_JEWELRY_TOPAZ_NECKLACE"_J, "Dane Topaz Necklace"}, {"MP005_S_NKLC_PNT_POR"_J, "PROVISION_JEWELRY_PORCELAIN_NECKLACE"_J, "Blakely Miniature Necklace"}, {"MP005_S_NKLC_SLV_PRL"_J, "PROVISION_JEWELRY_SLVR_PEARL_NECKLACE"_J, "Richelieu Amethyst Necklace"}};

	inline const RewardInfo Rings[]{{"MP005_S_RNG_CORAL"_J, "PROVISION_JEWELRY_CORAL_RING"_J, "Harland Coral Ring"}, {"MP005_S_RNG_DMND_ONYX"_J, "PROVISION_JEWELRY_ONYX_RING"_J, "Aubrey Onyx Ring"}, {"MP005_S_RNG_EMR_GLD"_J, "PROVISION_JEWELRY_EMERALD_RING"_J, "Bosque Emerald Ring"}, {"MP005_S_RNG_FRN_DMD"_J, "PROVISION_JEWELRY_FRENCH_DMND_RING"_J, "Beaulieux Diamond Ring"}, {"MP005_S_RNG_GLD_DMD"_J, "PROVISION_JEWELRY_YLWGLD_DMND_RING"_J, "Yates Diamond Ring"}, {"MP005_S_RNG_GLD_PRL"_J, "PROVISION_JEWELRY_PEARL_RING"_J, "Bonnard Pearl Ring"}, {"MP005_S_RNG_MNSTN"_J, "PROVISION_JEWELRY_MOON_RING"_J, "Pilgrim Moonstone Ring"}, {"MP005_S_RNG_PTRN_DMD"_J, "PROVISION_JEWELRY_WHTGLD_DMND_RING"_J, "Sackville Diamond Ring"}, {"MP005_S_RNG_TOP_WED"_J, "PROVISION_JEWELRY_TOPAZ_RING"_J, "Banais Topaz Ring"}, {"MP005_S_RNG_TRQ_GLD"_J, "PROVISION_JEWELRY_PERS_TURQ_RING"_J, "Magnate Turquoise Ring"}, {"MP005_S_RNG_TRQ_MOT"_J, "PROVISION_JEWELRY_TURQUOISE_RING"_J, "Thorburn Turquoise Ring"}};

	inline const RewardInfo TarotCards_Cups[]{{"MP005_S_CARDT_2C"_J, "DOCUMENT_CARD_TWO_CUPS"_J, "2 of Cups"}, {"MP005_S_CARDT_3C"_J, "DOCUMENT_CARD_THREE_CUPS"_J, "3 of Cups"}, {"MP005_S_CARDT_4C"_J, "DOCUMENT_CARD_FOUR_CUPS"_J, "4 of Cups"}, {"MP005_S_CARDT_5C"_J, "DOCUMENT_CARD_FIVE_CUPS"_J, "5 of Cups"}, {"MP005_S_CARDT_6C"_J, "DOCUMENT_CARD_SIX_CUPS"_J, "6 of Cups"}, {"MP005_S_CARDT_7C"_J, "DOCUMENT_CARD_SEVEN_CUPS"_J, "7 of Cups"}, {"MP005_S_CARDT_8C"_J, "DOCUMENT_CARD_EIGHT_CUPS"_J, "8 of Cups"}, {"MP005_S_CARDT_9C"_J, "DOCUMENT_CARD_NINE_CUPS"_J, "9 of Cups"}, {"MP005_S_CARDT_10C"_J, "DOCUMENT_CARD_TEN_CUPS"_J, "10 of Cups"}, {"MP005_S_CARDT_ACC"_J, "DOCUMENT_CARD_ACE_CUPS"_J, "Ace of Cups"}, {"MP005_S_CARDT_KIC"_J, "DOCUMENT_CARD_KING_CUPS"_J, "King of Cups"}, {"MP005_S_CARDT_KNC"_J, "DOCUMENT_CARD_KNIGHT_CUPS"_J, "Knight of Cups"}, {"MP005_S_CARDT_PAC"_J, "DOCUMENT_CARD_PAGE_CUPS"_J, "Page of Cups"}, {"MP005_S_CARDT_QUC"_J, "DOCUMENT_CARD_QUEEN_CUPS"_J, "Queen of Cups"}};

	inline const RewardInfo TarotCards_Pentacles[]{{"MP005_S_CARDT_2P"_J, "DOCUMENT_CARD_TWO_PENTACLES"_J, "2 of Pentacles"}, {"MP005_S_CARDT_3P"_J, "DOCUMENT_CARD_THREE_PENTACLES"_J, "3 of Pentacles"}, {"MP005_S_CARDT_4P"_J, "DOCUMENT_CARD_FOUR_PENTACLES"_J, "4 of Pentacles"}, {"MP005_S_CARDT_5P"_J, "DOCUMENT_CARD_FIVE_PENTACLES"_J, "5 of Pentacles"}, {"MP005_S_CARDT_6P"_J, "DOCUMENT_CARD_SIX_PENTACLES"_J, "6 of Pentacles"}, {"MP005_S_CARDT_7P"_J, "DOCUMENT_CARD_SEVEN_PENTACLES"_J, "7 of Pentacles"}, {"MP005_S_CARDT_8P"_J, "DOCUMENT_CARD_EIGHT_PENTACLES"_J, "8 of Pentacles"}, {"MP005_S_CARDT_9P"_J, "DOCUMENT_CARD_NINE_PENTACLES"_J, "9 of Pentacles"}, {"MP005_S_CARDT_10P"_J, "DOCUMENT_CARD_TEN_PENTACLES"_J, "10 of Pentacles"}, {"MP005_S_CARDT_ACP"_J, "DOCUMENT_CARD_ACE_PENTACLES"_J, "Ace of Pentacles"}, {"MP005_S_CARDT_KIP"_J, "DOCUMENT_CARD_KING_PENTACLES"_J, "King of Pentacles"}, {"MP005_S_CARDT_KNP"_J, "DOCUMENT_CARD_KNIGHT_PENTACLES"_J, "Knight of Pentacles"}, {"MP005_S_CARDT_PAP"_J, "DOCUMENT_CARD_PAGE_PENTACLES"_J, "Page of Pentacles"}, {"MP005_S_CARDT_QUP"_J, "DOCUMENT_CARD_QUEEN_PENTACLES"_J, "Queen of Pentacles"}};

	inline const RewardInfo TarotCards_Swords[]{{"MP005_S_CARDT_2S"_J, "DOCUMENT_CARD_TWO_SWORDS"_J, "2 of Swords"}, {"MP005_S_CARDT_3S"_J, "DOCUMENT_CARD_THREE_SWORDS"_J, "3 of Swords"}, {"MP005_S_CARDT_4S"_J, "DOCUMENT_CARD_FOUR_SWORDS"_J, "4 of Swords"}, {"MP005_S_CARDT_5S"_J, "DOCUMENT_CARD_FIVE_SWORDS"_J, "5 of Swords"}, {"MP005_S_CARDT_6S"_J, "DOCUMENT_CARD_SIX_SWORDS"_J, "6 of Swords"}, {"MP005_S_CARDT_7S"_J, "DOCUMENT_CARD_SEVEN_SWORDS"_J, "7 of Swords"}, {"MP005_S_CARDT_8S"_J, "DOCUMENT_CARD_EIGHT_SWORDS"_J, "8 of Swords"}, {"MP005_S_CARDT_9S"_J, "DOCUMENT_CARD_NINE_SWORDS"_J, "9 of Swords"}, {"MP005_S_CARDT_10S"_J, "DOCUMENT_CARD_TEN_SWORDS"_J, "10 of Swords"}, {"MP005_S_CARDT_ACS"_J, "DOCUMENT_CARD_ACE_SWORDS"_J, "Ace of Swords"}, {"MP005_S_CARDT_KIS"_J, "DOCUMENT_CARD_KING_SWORDS"_J, "King of Swords"}, {"MP005_S_CARDT_KNS"_J, "DOCUMENT_CARD_KNIGHT_SWORDS"_J, "Knight of Swords"}, {"MP005_S_CARDT_PAS"_J, "DOCUMENT_CARD_PAGE_SWORDS"_J, "Page of Swords"}, {"MP005_S_CARDT_QUS"_J, "DOCUMENT_CARD_QUEEN_SWORDS"_J, "Queen of Swords"}};

	inline const RewardInfo TarotCards_Wands[]{{"MP005_S_CARDT_2W"_J, "DOCUMENT_CARD_TWO_WANDS"_J, "2 of Wands"}, {"MP005_S_CARDT_3W"_J, "DOCUMENT_CARD_THREE_WANDS"_J, "3 of Wands"}, {"MP005_S_CARDT_4W"_J, "DOCUMENT_CARD_FOUR_WANDS"_J, "4 of Wands"}, {"MP005_S_CARDT_5W"_J, "DOCUMENT_CARD_FIVE_WANDS"_J, "5 of Wands"}, {"MP005_S_CARDT_6W"_J, "DOCUMENT_CARD_SIX_WANDS"_J, "6 of Wands"}, {"MP005_S_CARDT_7W"_J, "DOCUMENT_CARD_SEVEN_WANDS"_J, "7 of Wands"}, {"MP005_S_CARDT_8W"_J, "DOCUMENT_CARD_EIGHT_WANDS"_J, "8 of Wands"}, {"MP005_S_CARDT_9W"_J, "DOCUMENT_CARD_NINE_WANDS"_J, "9 of Wands"}, {"MP005_S_CARDT_10W"_J, "DOCUMENT_CARD_TEN_WANDS"_J, "10 of Wands"}, {"MP005_S_CARDT_ACW"_J, "DOCUMENT_CARD_ACE_WANDS"_J, "Ace of Wands"}, {"MP005_S_CARDT_KIW"_J, "DOCUMENT_CARD_KING_WANDS"_J, "King of Wands"}, {"MP005_S_CARDT_KNW"_J, "DOCUMENT_CARD_KNIGHT_WANDS"_J, "Knight of Wands"}, {"MP005_S_CARDT_PAW"_J, "DOCUMENT_CARD_PAGE_WANDS"_J, "Page of Wands"}, {"MP005_S_CARDT_QUW"_J, "DOCUMENT_CARD_QUEEN_WANDS"_J, "Queen of Wands"}};

	inline const RewardInfo Fossils[]{{0, "COLLECTIBLE_FOSSIL_CORAL"_J, ""}, {0, "COLLECTIBLE_FOSSIL_BIVALVE"_J, ""}, {0, "COLLECTIBLE_FOSSIL_BRACHIOPOD"_J, ""}, {0, "COLLECTIBLE_FOSSIL_BROW_HORN"_J, ""}, {0, "COLLECTIBLE_FOSSIL_CEPHALOPOD"_J, ""}, {0, "COLLECTIBLE_FOSSIL_TRILOBITE_CRYPTO"_J, ""}, {0, "COLLECTIBLE_FOSSIL_TRILOBITE_ISO"_J, ""}, {0, "COLLECTIBLE_FOSSIL_TOOTH_MEGA"_J, ""}, {0, "COLLECTIBLE_FOSSIL_NEO"_J, ""}, {0, "COLLECTIBLE_FOSSIL_STONE"_J, ""}, {0, "COLLECTIBLE_FOSSIL_PET_WOOD"_J, ""}, {0, "COLLECTIBLE_FOSSIL_PET_WOOD_RAINBOW"_J, ""}, {0, "COLLECTIBLE_FOSSIL_SEA_LILY"_J, ""}, {0, "COLLECTIBLE_FOSSIL_SEA_SCORPION"_J, ""}, {0, "COLLECTIBLE_FOSSIL_TOOTH_SERRATED"_J, ""}, {0, "COLLECTIBLE_FOSSIL_TAIL_SPIKE"_J, ""}, {0, "COLLECTIBLE_FOSSIL_TOE_CLAW"_J, ""}, {0, "COLLECTIBLE_FOSSIL_TOOTH_TREX"_J, ""}, {0, "COLLECTIBLE_FOSSIL_TULLY_MONSTER"_J, ""}, {0, "COLLECTIBLE_FOSSIL_PET_WOOD_YELLOW"_J, ""}};
	
	inline const RewardInfo Eggs[]{{0, "COLLECTIBLE_EGG_VULTURE"_J, ""}, {0, "COLLECTIBLE_EGG_LOON"_J, ""}, {0, "COLLECTIBLE_EGG_DUCK"_J, ""}, {0, "COLLECTIBLE_EGG_GOOSE"_J, ""}, {0, "COLLECTIBLE_EGG_HERON"_J, ""}, {0, "COLLECTIBLE_EGG_EGRET"_J, ""}, {0, "COLLECTIBLE_EGG_EAGLE"_J, ""}, {0, "COLLECTIBLE_EGG_HAWK"_J, ""}, {0, "COLLECTIBLE_EGG_SPOONBILL"_J, ""}, {0, "COLLECTIBLE_EGG_CONDOR"_J, ""}};
	
	inline const RewardInfo TreasureReward[]{{0, "REWARD_ABANDONED_LOOT_MALE"_J, "Treasure Reward"}};

	inline const RewardInfo CapitaleReward[]{{0, "REWARD_CAPITALE_CHEST_LARGE"_J, "Capitale Reward"}};

	inline const RewardInfo RegularXP[]{{0, "AWARD_XP_MISSION_COMPLETE_REWARD_XXL"_J, "25K XP Reward"}};

	inline const RewardInfo MoonshinerXP[]{{0, 0xCBA92A55, "Moonshine XP Reward"}};

	inline const RewardInfo TraderXP[]{{0, 0xB11109AB, "Trader XP Reward"}};

	inline const RewardInfo CollectorXP[]{{0, 0xA64F15F2, "Collector XP Reward"}};

	inline const RewardInfo NaturalistXP[]{{0, 0x05839847, "Naturalist XP Reward"}};

	inline const RewardInfo BountyHunterXP[]{{0, 0x5424CC1A, "Bounty Hunter XP Reward"}};

	inline const RewardInfo TraderGoods[]{{0, 0xFD780631, "Trader Goods"}};

	enum class eRewardType : int
	{
		GOLD_REWARDS,
		HEIRLOOMS,
		COINS,
		ALCBOTTLES,
		ARROWHEADS,
		BRACELETS,
		EARRINGS,
		NECKLACES,
		RINGS,
		TAROTCARDS_CUPS,
		TAROTCARDS_PENTACLES,
		TAROTCARDS_SWORDS,
		TAROTCARDS_WANDS,
		FOSSILS,
		EGGS,
		TREASURE,
		CAPITALE,
		XP,
		MOONSHINERXP,
		TRADERXP,
		COLLECTORXP,
		NATURALISTXP,
		BOUNTYHUNTERXP,
		TRADERGOODS,
	};

	void GiveRequestedRewards(std::vector<eRewardType> rewards);
	void GiveReward(const RewardInfo& info);
	void GiveScriptReward(const RewardInfo& info, bool loottable = true);
}